const fs = require('fs');
const axios = require('axios');

const COUNTRY_CODES = [
    { "id": "AO" },
    { "id": "BF" },
    { "id": "BI" },
    { "id": "BJ" },
    { "id": "BW" },
    { "id": "CD" },
    { "id": "CF" },
    { "id": "CG" },
    { "id": "CI" },
    { "id": "CM" },
    { "id": "DJ" },
    { "id": "DZ" },
    { "id": "EG" },
    { "id": "ER" },
    { "id": "ET" },
    { "id": "GA" },
    { "id": "GH" },
    { "id": "GM" },
    { "id": "GN" },
    { "id": "GQ" },
    { "id": "GW" },
    { "id": "KE" },
    { "id": "LR" },
    { "id": "LS" },
    { "id": "LY" },
    { "id": "MA" },
    { "id": "MG" },
    { "id": "ML" },
    { "id": "MR" },
    { "id": "MW" },
    { "id": "MZ" },
    { "id": "NA" },
    { "id": "NE" },
    { "id": "NG" },
    { "id": "RW" },
    { "id": "SD" },
    { "id": "SL" },
    { "id": "SN" },
    { "id": "SO" },
    { "id": "SS" },
    { "id": "SZ" },
    { "id": "TD" },
    { "id": "TG" },
    { "id": "TN" },
    { "id": "TZ" },
    { "id": "UG" },
    { "id": "ZA" },
    { "id": "ZM" },
    { "id": "ZW" },
    { "id": "EH" },
];

const FILE_PATH = 'resources/js/modules/africanCountries.js';

const getCountryInfo = async (country) => {
    const id = country.id;

    if (id == "EH") {
        return {
            iso2Code: id,
            name: "Western Sahara",
            capitalCity: undefined,
            longitude: undefined,
            latitude: undefined,
        }
    }
    const response = await axios.get(`http://api.worldbank.org/v2/country/${id}?format=json`);
    
    const data = response.data[1][0];

    return {
        iso2Code: id,
        name: data.name,
        capitalCity: data.capitalCity,
        longitude: Number(data.longitude),
        latitude: Number(data.latitude),
    };
};

const getCountries = async () => {
    const countries = {};

    for (let i = 0; i < COUNTRY_CODES.length; ++i) {
        try {
            const info = await getCountryInfo(COUNTRY_CODES[i]);
            countries[COUNTRY_CODES[i].id] = info;
        } catch (err) {
            console.error(`There is an error here for ${COUNTRY_CODES[i].id}`, err);
        }
    }

    return countries;
};

const generateAfricanCountriesJS = async(countries) => {
    const text = `/**
 * This file is autogenerated by getCountries.js. DO NOT modify directly.
 */ 
const { Map } = require('immutable');

const countries = ${JSON.stringify(countries, null, '\t')};

export default Map(countries);
`;
    
    fs.writeFileSync(FILE_PATH, text);
    console.log(`Done: Written data to ${FILE_PATH}`);
}

getCountries()
    .then(generateAfricanCountriesJS);
