version: "3.7"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - './nginx/conf.d:/etc/nginx/conf.d'
      - './nginx/server.crt:/etc/nginx/server.crt'
      - './nginx/server.key:/etc/nginx/server.key'
    ports:
      - '80:80'
      - '443:443'
      - '8000:8000'
    restart: unless-stopped
