import { List } from "immutable";

export default List([
	"Access to clean water",
	"Access to education",
	"Access to energy",
	"Access to financial services",
	"Affordable housing",
	"Agriculture productivity",
	"Capacity building",
	"Community development",
	"Employment generation",
	"Equality and empowerment",
	"Food security",
	"Generate funds for charitable giving",
	"Health improvement",
	"Income/productivity growth",
	"Access to information",
	"Natural resources/biodiversity",
	"Pollution prevention and waste management",
	"Sustainable energy/fuel efficiency",
	"Sustainable land use",
	"Support for high-impact entrepreneurs",
	"Support for women and girls",
]);
